### ISSUE TITLE
train_ppon.py import errors

### ISSUE THREAD

**Issue by sean-horton** [victorca25/BasicSR#28]
I tried train_ppon.py and got an import error on 

```
from models.modules.LPIPS import compute_dists as lpips
```

I tried commenting it out and the usage of lpips and there seemed to be other import errors. 

I've not tried test_ppon.py, but maybe that has errors too.

**Comment by victorca25** [comment]
Thanks for trying it out! The PPON codes have not been updated to the latest changes in the repo, it's on the TODO list

**Comment by victorca25** [comment]
@sean-horton PPON training is now fully working in my local test repo, will commit it soon, after I do some more testing to check everything works fine

**Comment by sean-horton** [comment]
Awesome, I look forward to trying it out. Thanks!

**Comment by victorca25** [comment]
@sean-horton the reworked code for PPON is now up. Now you can train PPON using the normal train.py file, only need to change these options in the option file:

model: ppon
...
which_model_G: ppon
    mode: CNA
    nf: 64
    nb: 24
    in_nc: 3
    out_nc: 3
    group: 1
...
p1_losses: [pix] # from the paper: l1 pixel_weigh: 1
p2_losses: [pix-multiscale, ms-ssim] # from the paper: multiscale_weight: 1, ms-ssim_weight: 1
p3_losses: [fea] # from the paper: VGG feature_weight: 1 gan_weight: 0.005
ppon_stages: [1000, 2000] # The first value here is where phase 2 (structure) will start and the second is where phase 3 (features) starts

Note that you may need to adjust your scheduler and coordinate the ppon_stages to match, the original paper used "StepLR_Restart".
