### ISSUE TITLE
NameError: name 'log_dir' is not defined

### ISSUE THREAD

**Issue by GuusDeKroon** [victorca25/BasicSR#32]
Hey,
When trying to train, I got the following error. Does anyone know how to fix it?

Traceback (most recent call last):
  File "train.py", line 65, in configure_loggers
    tb_logger = SummaryWriter(log_dir=log_dir)
NameError: name 'log_dir' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 379, in <module>
    main()
  File "train.py", line 351, in main
    loggers = configure_loggers(opt)
  File "train.py", line 69, in configure_loggers
    tb_logger = SummaryWriter(logdir=log_dir)
NameError: name 'log_dir' is not defined

E:\BasicSR-master\codes>

**Comment by victorca25** [comment]
Thanks for the issue! Will fix the missing variable name in an upcomming commit

**Comment by victorca25** [comment]
This bug should now be fixed!
