### ISSUE TITLE
lam < 0 or lam contains NaNs

### ISSUE THREAD

**Issue by mansum6** [victorca25/BasicSR#44]
I got error( 'lam < 0 or lam contains NaNs') on some images in
at https://github.com/victorca25/BasicSR/blob/14aced7d1049a283761c145f3cf300a94c6ac4b9/codes/dataops/augmentations.py#L786
I just modified to perform gaussian noise on the error images

    try:
      noise_img = np.random.poisson(img_LR * vals) / float(vals)
    except ValueError:
      print("Poissoning Err,Just Gaussing it")
      compression = np.random.uniform(10, 50) #randomize quality between 10 and 50%
      encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), compression] #encoding parameters
      # encode
      is_success, encimg = cv2.imencode('.jpg', img_LR, encode_param) 
      
      # decode
      noise_img = cv2.imdecode(encimg, 1) 
      noise_img = noise_img.astype(np.uint8)

**Comment by victorca25** [comment]
Hello! In your configuration yaml,please change from using the "LRHR" (or LRHROTF) dataloader to "LRHRC", now the augmentations used by default are in https://github.com/victorca25/opencv_transforms and are more up to date. 

The error should not happen in that case, but thanks for creating the issue!

**Comment by mansum6** [comment]
Using "LRHRC" fixed it. Thanks
