### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB

### ISSUE THREAD

**Issue by mansum6** [victorca25/BasicSR#45]
On Colab restarting training again results in following error:  

_File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/BasicSR/codes/models/modules/architectures/block.py", line 428, in forward
    sampled_noise = self.noise.repeat(*x.size()).normal_() * scale
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.78 GiB total capacity; 14.32 GiB already allocated; 20.75 MiB free; 14.46 GiB reserved in total by PyTorch)_

The only way to restart training was to reduce batch all the way from **64 to 3**

I've **tried running** following commands to no avail: 
gc.collect()
torch.cuda.empty_cache()

There seems to a **resolution** here:
https://discuss.pytorch.org/t/how-can-we-release-gpu-memory-cache/14530/27

**Comment by victorca25** [comment]
Hello! I haven't seen that behavior, but will try to replicate it. What are your CUDA, Python and Pytorch versions?

**Comment by mansum6** [comment]
On Colab
Cuda:V11.0.221
Torch: 1.8.1+cu101
Python 3.7.10.

Anyways, i did change the scale from 4x to 1x, but didn't see why this would lead to such a drastic reduction in batch size.
Once the training began, it was only using around 9 GB of 16 GB total VRAM.

**Comment by victorca25** [comment]
Changing the scale from 4x to 1x means that the input size will be the same as the output.

By default the output size is 128x128, meaning the input size is 32x32 with 4x scale. If using 1x scale, the input is 4 times larger in both dimensions, which you also multiply by the batch size and then pass this batch through the entirety of the model, consuming a lot more memory than the 4x case.
