### ISSUE TITLE
Results are blue

### ISSUE THREAD

**Issue by ajeema** [victorca25/BasicSR#47]
I'm using the test.py as per the instruction and my results are blue. How can I run upscaling to produce proper results?

**Comment by victorca25** [comment]
Hello! Maybe there's a missing conversion between RGB and OpenCV's BGR channel format. I would have to check where this could be happening, but can you try to do the upscaling using: https://github.com/victorca25/iNNfer instead? It should be easier to use and I've tested it a lot recently.

**Comment by ajeema** [comment]
ok great, I will try that. Thank you

**Comment by mmmoussa96** [comment]
was this fixed? I'm having a similar issue (where it's green). I converted images to npy used their sub-images as per the guide here: https://github.com/victorca25/BasicSR/wiki/IO-speed

**Comment by victorca25** [comment]
@mmmoussa96 Hello! Yours is a different situation, but it sounds potentially like an OpenCV BGR -> RGB conversion issue.

OpenCV by default reads images in BGR channel order, which are converted to RGB when converted to tensor for training. 

Before line 158 here: https://github.com/victorca25/BasicSR/blob/master/codes/data/aligned_dataset.py, you can use the tmp_vis() debug function to visualize the images (uncomment line 9) and check if that’s the problem.

The function should look something like:

tmp_vis(img_A, False)

Try that and let me know how they look like.

**Comment by mmmoussa96** [comment]
Yes, I used PIL to pre-process the images and I guess forgot to convert RGB -> BGR. Did that, trained the images and now I'm getting this blue image described. Will use iNNfer now. Thank you!
